### ISSUE TITLE
hardware requirements

### ISSUE THREAD

**Issue by zy158** [truthless11/HRL-RE#6]
I meet the question:
`THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhaoy/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/zhaoy/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/zhaoy/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 95, in rebuild_storage_cuda
    torch.cuda._lazy_init()
  File "/home/zhaoy/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cu:25`
what is your model's hardware requirements?

**Comment by truthless11** [comment]
The relevant information of our equipment is as follows:
OS: Ubuntu 16.04.5
GPU: TITAN Xp
CUDA 8.0.61
python 3.6.6
I'm not sure about the hardware issue, though I don't think our code will occupy much memory. Plz double-check that your driver is installed correctly.
