### ISSUE TITLE
multi processes problem

### ISSUE THREAD

**Issue by eclipse-du** [truthless11/HRL-RE#7]
First to thank your project, I do really think HRL-RE is a gooooood idea.
However, when i use colab to train my model, I find it hard to use 4 process, so i change the process into 2, then the problem shows as below:

Starting training service, overall process number:  2
training epoch  0
Process  1  start service.
Process  0  start service.
Process Process-2:
Process Process-2:
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/My Drive/workspace/HRL-RE-master/code/TrainProcess.py", line 55, in worker
    acc, cnt, tot, loss = workProcess(model, datas, sample_round, mode)
  File "/content/drive/My Drive/workspace/HRL-RE-master/code/TrainProcess.py", line 25, in workProcess
    preoptions, preactions)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/workspace/HRL-RE-master/code/Model.py", line 80, in forward
    prehid, prec = self.preLSTML(wvs[x], (prehid, prec))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 723, in forward
    self.check_forward_input(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 563, in check_forward_input
    if input.size(1) != self.input_size:
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

pytorch version is 1.0.1, so i don't know what the problem can be. By the way, i can not find log "Process Process-2:" in anywhere. Was the problem due to the version or pytorch multi-process instead? Thanks for any reply on this issue

**Comment by chenjiayu1502** [comment]
pytorch version is 0.3.1 or 0.3.0
